version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app

    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql

volumes:
  db:
