import { type AppType } from 'next/app'
import { type Session } from 'next-auth'
import { SessionProvider } from 'next-auth/react'

import '../styles/globals.css'
import Head from 'next/head'
import Navbar from '../components/layout/Navbar'

import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

const client = new QueryClient()

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <QueryClientProvider client={client}>
      <SessionProvider session={session}>
        <Head>
          <title>TRG Mulabdić</title>
          <meta name='description' content='Generated by create-t3-app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        {/* {!article_id && <Navbar />} */}
        <Navbar />
        <Component {...pageProps} />
      </SessionProvider>
    </QueryClientProvider>
  )
}

export default MyApp
