import { type AppType } from 'next/app'
import { type Session } from 'next-auth'
import { SessionProvider } from 'next-auth/react'

import { api } from '../utils/api'

import '../styles/globals.css'
import Head from 'next/head'
import Navbar from '../components/layout/Navbar'
// import { useRouter } from 'next/router'

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  // const router = useRouter()
  // const { article_id } = router.query

  return (
    <SessionProvider session={session}>
      <Head>
        <title>TRG Mulabdić</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* {!article_id && <Navbar />} */}
      <Navbar />
      <Component {...pageProps} />
    </SessionProvider>
  )
}

export default api.withTRPC(MyApp)
